# Import Packages

In [1]:
%matplotlib inline
import pandas as pd
import warnings
import seaborn as sns
import matplotlib.pyplot as plt
import pickle
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# Read the 2000 Full count csv, take a look, and isolate NYC

In [2]:
df_00 = pd.read_csv('DATA/LTDB_Std_All_fullcount/LTDB_Std_2000_fullcount.csv',sep=',', engine='python')      
print(df_00.shape)
print(df_00[df_00.state.eq('NY')].county.value_counts().head())
df_00.head()

(72693, 51)
Kings County       753
Queens County      665
Bronx County       338
Suffolk County     322
New York County    287
Name: county, dtype: int64

      TRTID10 state                county               tract  placefp10  cbsa10  metdiv10  ccflag10        POP00      NHWHT00      NHBLK00      NTV00     ASIAN00       HISP00  HAW00    INDIA00  CHINA00     FILIP00    JAPAN00   KOREA00  VIET00        MEX00       PR00  CUBAN00         HU00      VAC00        OHU00     A18UND00     A60UP00     A75UP00     AGEWHT00   A15WHT00    A60WHT00     AGEBLK00    A15BLK00    A60BLK00     AGEHSP00     A15HSP00    A60HSP00   AGENTV00  A15NTV00  A60NTV00    AGEASN00   A15ASN00   A60ASN00     FAMILY00       FHH00       OWN00      RENT00 GlobD00      GlobG00
0  1001020100    AL        Autauga County    Census Tract 201      62328   33860     99999         0  1920.974695  1722.977295   144.998093  28.999619    7.999895    11.999842    0.0   3.999947      0.0    0.999987   0.999987  1.999974     0.0     3.999947   1.999974      0.0   768.989868  92.998772   675.991089   518.993164  259.996582   68.999092  1722.977295  402.99469  244.996765   140.998138   30.999592   12.999828    11.999842     3.999947    0.999987  14.999803  4.999934       0.0    6.999908   1.999974   0.999987   531.992981   58.999222  517.993164  157.997925      bw  White Black
1  6083002402    CA  Santa Barbara County  Census Tract 24.02      69196   42060     99999         1  6742.000000  1573.000000   126.000000  44.000000  272.000000  4700.000000   11.0  24.000000     18.0  229.000000  46.000000  3.000000     3.0  4159.000000  20.000000      4.0  1828.000000  52.000000  1776.000000  2484.000000  675.000000  286.000000  1573.000000  296.00000  466.000000   103.000000   35.000000    7.000000  4700.000000  1830.000000  154.000000  25.000000  3.000000       3.0  231.000000  44.000000  37.000000  1367.000000  218.000000  857.000000  919.000000     wha   Dual immig
2  1001020200    AL        Autauga County    Census Tract 202      62328   33860     99999         0  1892.000000   671.000000  1177.000000  12.000000   12.000000    16.000000    0.0   0.000000      1.0    3.000000   1.000000  6.000000     0.0    11.000000   1.000000      3.0   731.000000  67.000000   664.000000   530.000000  282.000000  103.000000   671.000000  156.00000  120.000000  1163.000000  302.000000  158.000000    16.000000     5.000000    1.000000   6.000000  0.000000       0.0    7.000000   1.000000   0.000000   494.000000  121.000000  452.000000  212.000000      bw  White Black
3  6083002102    CA  Santa Barbara County  Census Tract 21.02      69196   42060     99999         1  2041.000000  1204.000000    57.000000  19.000000   60.000000   696.000000    2.0   1.000000      7.0   27.000000  21.000000  3.000000     5.0   579.000000  17.000000      4.0   773.000000  25.000000   748.000000   535.000000  446.000000  192.000000  1204.000000  206.00000  363.000000    53.000000   16.000000    3.000000   696.000000   248.000000   61.000000   8.000000  1.000000       1.0   47.000000   2.000000  14.000000   501.000000   56.000000  484.000000  264.000000     wha   Dual immig
4  1001020300    AL        Autauga County    Census Tract 203      62328   33860     99999         0  3339.000000  2738.000000   498.000000  16.000000   27.000000    55.000000    1.0   0.000000      3.0    3.000000   8.000000  2.000000     1.0    29.000000  16.000000      0.0  1263.000000  61.000000  1202.000000   960.000000  594.000000  229.000000  2738.000000  691.00000  499.000000   491.000000  132.000000   84.000000    55.000000    18.000000    3.000000   7.000000  2.000000       0.0   23.000000   3.000000   6.000000   920.000000  118.000000  869.000000  333.000000      bw  White Black

In [3]:
nyc_00 = df_00[ (df_00['state'].eq('NY'))]
nyc_00 = nyc_00[    (nyc_00['county'].eq('Bronx County')) 
                  | (nyc_00['county'].eq('Kings County')) 
                  | (nyc_00['county'].eq('Queens County')) 
                  | (nyc_00['county'].eq('New York County'))]
print(nyc_00.shape)
nyc_00.head()

(2043, 51)

           TRTID10 state        county            tract  placefp10  cbsa10  metdiv10  ccflag10    POP00  NHWHT00  NHBLK00  NTV00  ASIAN00  HISP00  HAW00  INDIA00  CHINA00  FILIP00  JAPAN00  KOREA00  VIET00  MEX00    PR00  CUBAN00    HU00  VAC00   OHU00  A18UND00  A60UP00  A75UP00  AGEWHT00  A15WHT00  A60WHT00  AGEBLK00  A15BLK00  A60BLK00  AGEHSP00  A15HSP00  A60HSP00  AGENTV00  A15NTV00  A60NTV00  AGEASN00  A15ASN00  A60ASN00  FAMILY00  FHH00  OWN00  RENT00 GlobD00   GlobG00
54050  36005000100    NY  Bronx County   Census Tract 1      51000   35620     35644         1  12780.0   1091.0   7747.0   17.0     64.0  3443.0    0.0      2.0      0.0      0.0      0.0      0.0     0.0   29.0    97.0      2.0     0.0    0.0     0.0     481.0    125.0     22.0    1091.0       0.0      33.0    7741.0       1.0      52.0    3443.0       0.0      35.0      17.0       0.0       0.0      55.0       0.0       1.0       0.0    0.0    0.0     0.0      bh  Minority
54052  36005000200    NY  Bronx County   Census Tract 2      51000   35620     35644         1   3545.0    209.0    807.0    8.0     25.0  2464.0    0.0     21.0      1.0      2.0      4.0      0.0     0.0   37.0  1842.0     17.0  1213.0   85.0  1128.0    1093.0    536.0    124.0     209.0      37.0      69.0     771.0     209.0      96.0    2464.0     707.0     357.0       6.0       1.0       0.0      18.0       1.0       3.0     860.0  199.0  637.0   491.0      bh  Minority
54054  36005000400    NY  Bronx County   Census Tract 4      51000   35620     35644         1   3314.0    174.0    738.0    9.0     85.0  2255.0    0.0     34.0     27.0      8.0      2.0     18.0     0.0   19.0  1472.0     35.0  1108.0   57.0  1051.0    1008.0    368.0    101.0     174.0      31.0      50.0     717.0     187.0      58.0    2255.0     638.0     254.0       6.0       1.0       0.0      83.0      18.0       2.0     818.0  179.0  633.0   418.0     bha  Minority
54056  36005001600    NY  Bronx County  Census Tract 16      51000   35620     35644         1   5237.0    250.0   1625.0   25.0     56.0  3250.0    0.0     31.0     17.0     12.0      5.0      3.0     1.0   38.0  2246.0     82.0  1853.0   43.0  1810.0    1542.0    897.0    289.0     250.0      31.0     138.0    1568.0     460.0     197.0    3250.0     844.0     543.0      23.0       6.0       1.0      36.0       6.0       9.0    1299.0  479.0  291.0  1519.0      bh  Minority
54058  36005001900    NY  Bronx County  Census Tract 19      51000   35620     35644         1   1584.0     91.0    471.0    9.0     15.0   987.0    0.0      7.0      1.0      9.0      0.0      0.0     1.0  100.0   578.0     20.0   510.0   93.0   417.0     463.0    140.0     35.0      91.0      17.0      19.0     454.0     138.0      20.0     987.0     266.0      97.0       5.0       0.0       0.0      15.0       0.0       4.0     239.0   64.0   84.0   333.0      bh  Minority

## Reworking the data so that the percentage of each population category is shown.

The percentages will be much more meaningful than the total counts, especially as population increases overall.

In [4]:
nyc_00.columns.values

array(['TRTID10', 'state', 'county', 'tract', 'placefp10', 'cbsa10',
       'metdiv10', 'ccflag10', 'POP00', 'NHWHT00', 'NHBLK00', 'NTV00',
       'ASIAN00', 'HISP00', 'HAW00', 'INDIA00', 'CHINA00', 'FILIP00',
       'JAPAN00', 'KOREA00', 'VIET00', 'MEX00', 'PR00', 'CUBAN00', 'HU00',
       'VAC00', 'OHU00', 'A18UND00', 'A60UP00', 'A75UP00', 'AGEWHT00',
       'A15WHT00', 'A60WHT00', 'AGEBLK00', 'A15BLK00', 'A60BLK00',
       'AGEHSP00', 'A15HSP00', 'A60HSP00', 'AGENTV00', 'A15NTV00',
       'A60NTV00', 'AGEASN00', 'A15ASN00', 'A60ASN00', 'FAMILY00',
       'FHH00', 'OWN00', 'RENT00', 'GlobD00', 'GlobG00'], dtype=object)

In [5]:
ppl_cols = list(nyc_00.columns.values[9:-4])
house_cols = list(nyc_00.columns.values[-4:-2])

In [6]:
def pipeline(df,ppl_list,house_list):
    for x in df.columns.values:
        if x in ppl_list:
            df[x + '%'] = 100 * df[x] / df['POP00']
        elif x in house_list:
            df[x + '%'] = 100 * df[x] / df['HU00']
    # the percentage of non 
    df['NONWHT00%'] = 100*(df.iloc[:,10:14].sum(1)/df['POP00'])
    df.drop(columns = ['HU00%'], axis = 1, inplace = True)
    df.drop(df.columns[9:51],axis=1,inplace=True)
    df.drop(df.columns[4:8],axis=1,inplace=True)

In [7]:
nyc_00p = nyc_00.copy()

pipeline(nyc_00p,ppl_cols,house_cols)
nyc_00p.head()

           TRTID10 state        county            tract    POP00  NHWHT00%   NHBLK00%    NTV00%  ASIAN00%    HISP00%  HAW00%  INDIA00%  CHINA00%  FILIP00%  JAPAN00%  KOREA00%   VIET00%    MEX00%      PR00%  CUBAN00%    VAC00%     OHU00%  A18UND00%   A60UP00%  A75UP00%  AGEWHT00%  A15WHT00%  A60WHT00%  AGEBLK00%  A15BLK00%  A60BLK00%  AGEHSP00%  A15HSP00%  A60HSP00%  AGENTV00%  A15NTV00%  A60NTV00%  AGEASN00%  A15ASN00%  A60ASN00%  FAMILY00%    FHH00%     OWN00%    RENT00%  NONWHT00%
54050  36005000100    NY  Bronx County   Census Tract 1  12780.0  8.536776  60.618153  0.133020  0.500782  26.940532     0.0  0.015649  0.000000  0.000000  0.000000  0.000000  0.000000  0.226917   0.758998  0.015649  0.000000   0.000000   3.763693   0.978091  0.172144   8.536776   0.000000   0.258216  60.571205   0.007825   0.406886  26.940532   0.000000   0.273865   0.133020   0.000000   0.000000   0.430360   0.000000   0.007825   0.000000  0.000000        NaN        NaN  88.192488
54052  36005000200    NY  Bronx County   Census Tract 2   3545.0  5.895628  22.764457  0.225670  0.705219  69.506347     0.0  0.592384  0.028209  0.056417  0.112835  0.000000  0.000000  1.043724  51.960508  0.479549  2.397743  31.819464  30.832158  15.119887  3.497884   5.895628   1.043724   1.946403  21.748942   5.895628   2.708039  69.506347  19.943583  10.070522   0.169252   0.028209   0.000000   0.507757   0.028209   0.084626  24.259520  5.613540  52.514427  40.478153  93.201693
54054  36005000400    NY  Bronx County   Census Tract 4   3314.0  5.250453  22.269161  0.271575  2.564876  68.044659     0.0  1.025951  0.814725  0.241400  0.060350  0.543150  0.000000  0.573325  44.417622  1.056126  1.719976  31.713941  30.416415  11.104406  3.047677   5.250453   0.935425   1.508751  21.635486   5.642728   1.750151  68.044659  19.251660   7.664454   0.181050   0.030175   0.000000   2.504526   0.543150   0.060350  24.683162  5.401328  57.129964  37.725632  93.150272
54056  36005001600    NY  Bronx County  Census Tract 16   5237.0  4.773725  31.029215  0.477373  1.069314  62.058430     0.0  0.591942  0.324613  0.229139  0.095475  0.057285  0.019095  0.725606  42.887149  1.565782  0.821081  34.561772  29.444338  17.128127  5.518427   4.773725   0.591942   2.635096  29.940806   8.783655   3.761696  62.058430  16.116097  10.368532   0.439183   0.114569   0.019095   0.687416   0.114569   0.171854  24.804277  9.146458  15.704263  81.975175  94.634333
54058  36005001900    NY  Bronx County  Census Tract 19   1584.0  5.744949  29.734848  0.568182  0.946970  62.310606     0.0  0.441919  0.063131  0.568182  0.000000  0.000000  0.063131  6.313131  36.489899  1.262626  5.871212  26.325758  29.229798   8.838384  2.209596   5.744949   1.073232   1.199495  28.661616   8.712121   1.262626  62.310606  16.792929   6.123737   0.315657   0.000000   0.000000   0.946970   0.000000   0.252525  15.088384  4.040404  16.470588  65.294118  93.560606

## Census tracts with small amounts of people will be dropped. Not an accurate representation

In [8]:
print(nyc_00p.POP00.median())
print(nyc_00p.POP00.mean())

3332.907892
3702.667645596257

In [9]:
nyc_00p = nyc_00p[nyc_00p['POP00'].gt(700)]
print(nyc_00p.shape)
nyc_00p.head()

(1984, 45)

           TRTID10 state        county            tract    POP00  NHWHT00%   NHBLK00%    NTV00%  ASIAN00%    HISP00%  HAW00%  INDIA00%  CHINA00%  FILIP00%  JAPAN00%  KOREA00%   VIET00%    MEX00%      PR00%  CUBAN00%    VAC00%     OHU00%  A18UND00%   A60UP00%  A75UP00%  AGEWHT00%  A15WHT00%  A60WHT00%  AGEBLK00%  A15BLK00%  A60BLK00%  AGEHSP00%  A15HSP00%  A60HSP00%  AGENTV00%  A15NTV00%  A60NTV00%  AGEASN00%  A15ASN00%  A60ASN00%  FAMILY00%    FHH00%     OWN00%    RENT00%  NONWHT00%
54050  36005000100    NY  Bronx County   Census Tract 1  12780.0  8.536776  60.618153  0.133020  0.500782  26.940532     0.0  0.015649  0.000000  0.000000  0.000000  0.000000  0.000000  0.226917   0.758998  0.015649  0.000000   0.000000   3.763693   0.978091  0.172144   8.536776   0.000000   0.258216  60.571205   0.007825   0.406886  26.940532   0.000000   0.273865   0.133020   0.000000   0.000000   0.430360   0.000000   0.007825   0.000000  0.000000        NaN        NaN  88.192488
54052  36005000200    NY  Bronx County   Census Tract 2   3545.0  5.895628  22.764457  0.225670  0.705219  69.506347     0.0  0.592384  0.028209  0.056417  0.112835  0.000000  0.000000  1.043724  51.960508  0.479549  2.397743  31.819464  30.832158  15.119887  3.497884   5.895628   1.043724   1.946403  21.748942   5.895628   2.708039  69.506347  19.943583  10.070522   0.169252   0.028209   0.000000   0.507757   0.028209   0.084626  24.259520  5.613540  52.514427  40.478153  93.201693
54054  36005000400    NY  Bronx County   Census Tract 4   3314.0  5.250453  22.269161  0.271575  2.564876  68.044659     0.0  1.025951  0.814725  0.241400  0.060350  0.543150  0.000000  0.573325  44.417622  1.056126  1.719976  31.713941  30.416415  11.104406  3.047677   5.250453   0.935425   1.508751  21.635486   5.642728   1.750151  68.044659  19.251660   7.664454   0.181050   0.030175   0.000000   2.504526   0.543150   0.060350  24.683162  5.401328  57.129964  37.725632  93.150272
54056  36005001600    NY  Bronx County  Census Tract 16   5237.0  4.773725  31.029215  0.477373  1.069314  62.058430     0.0  0.591942  0.324613  0.229139  0.095475  0.057285  0.019095  0.725606  42.887149  1.565782  0.821081  34.561772  29.444338  17.128127  5.518427   4.773725   0.591942   2.635096  29.940806   8.783655   3.761696  62.058430  16.116097  10.368532   0.439183   0.114569   0.019095   0.687416   0.114569   0.171854  24.804277  9.146458  15.704263  81.975175  94.634333
54058  36005001900    NY  Bronx County  Census Tract 19   1584.0  5.744949  29.734848  0.568182  0.946970  62.310606     0.0  0.441919  0.063131  0.568182  0.000000  0.000000  0.063131  6.313131  36.489899  1.262626  5.871212  26.325758  29.229798   8.838384  2.209596   5.744949   1.073232   1.199495  28.661616   8.712121   1.262626  62.310606  16.792929   6.123737   0.315657   0.000000   0.000000   0.946970   0.000000   0.252525  15.088384  4.040404  16.470588  65.294118  93.560606

In [10]:
nyc_00p.isna().sum()

TRTID10      0
state        0
county       0
tract        0
POP00        0
NHWHT00%     0
NHBLK00%     0
NTV00%       0
ASIAN00%     0
HISP00%      0
HAW00%       0
INDIA00%     0
CHINA00%     0
FILIP00%     0
JAPAN00%     0
KOREA00%     0
VIET00%      0
MEX00%       0
PR00%        0
CUBAN00%     0
VAC00%       0
OHU00%       0
A18UND00%    0
A60UP00%     0
A75UP00%     0
AGEWHT00%    0
A15WHT00%    0
A60WHT00%    0
AGEBLK00%    0
A15BLK00%    0
A60BLK00%    0
AGEHSP00%    0
A15HSP00%    0
A60HSP00%    0
AGENTV00%    0
A15NTV00%    0
A60NTV00%    0
AGEASN00%    0
A15ASN00%    0
A60ASN00%    0
FAMILY00%    0
FHH00%       0
OWN00%       1
RENT00%      1
NONWHT00%    0
dtype: int64

### We only have two NaNs left, those will just be replaced with 0's.

In [11]:
nyc_00p['OWN00%'] = nyc_00p['OWN00%'].fillna(0)
nyc_00p['RENT00%'] = nyc_00p['RENT00%'].fillna(0)
nyc_00p.isna().sum()

TRTID10      0
state        0
county       0
tract        0
POP00        0
NHWHT00%     0
NHBLK00%     0
NTV00%       0
ASIAN00%     0
HISP00%      0
HAW00%       0
INDIA00%     0
CHINA00%     0
FILIP00%     0
JAPAN00%     0
KOREA00%     0
VIET00%      0
MEX00%       0
PR00%        0
CUBAN00%     0
VAC00%       0
OHU00%       0
A18UND00%    0
A60UP00%     0
A75UP00%     0
AGEWHT00%    0
A15WHT00%    0
A60WHT00%    0
AGEBLK00%    0
A15BLK00%    0
A60BLK00%    0
AGEHSP00%    0
A15HSP00%    0
A60HSP00%    0
AGENTV00%    0
A15NTV00%    0
A60NTV00%    0
AGEASN00%    0
A15ASN00%    0
A60ASN00%    0
FAMILY00%    0
FHH00%       0
OWN00%       0
RENT00%      0
NONWHT00%    0
dtype: int64

In [12]:
nyc_00p.to_pickle('PKL/nyc_00p.pkl')

# Read the 2010 Full count csv and repeat the process as in 2000

In [13]:
df_10 = pd.read_csv('DATA/LTDB_Std_All_fullcount/LTDB_Std_2010_fullcount.csv',sep=',', engine='python')      
print(df_10.shape)
df_10[df_10.state.eq('NY')].county.value_counts().head()

(74002, 47)

Kings County       761
Queens County      669
Bronx County       339
Suffolk County     323
New York County    288
Name: county, dtype: int64

### Isolate NYC

In [14]:
nyc_10 = df_10[ (df_10['state'].eq('NY'))]
nyc_10 = nyc_10[    (nyc_10['county'].eq('Bronx County')) 
                  | (nyc_10['county'].eq('Kings County')) 
                  | (nyc_10['county'].eq('Queens County')) 
                  | (nyc_10['county'].eq('New York County'))]
print(nyc_10.shape)
nyc_10.head(1)

(2057, 47)

           tractid state        county           tract  pop10  nhwht10  nhblk10  ntv10  asian10  hisp10  haw10  india10  china10  filip10  japan10  korea10  viet10  mex10  pr10  cuban10  family10  fhh10  hu10  vac10  ohu10  own10  rent10  a18und10  a60up10  a75up10  agewht10  a15wht10  a60wht10  ageblk10  a15blk10  a60blk10  agehsp10  a15hsp10  a60hsp10  ageasn10  a15asn10  a60asn10  agentv10  a15ntv10  a60ntv10 GlobD10   GlobG10
55589  36005000100    NY  Bronx County  Census Tract 1  11091      782     6208     26       39    3779      0        7        3        0        0        0       0    264   353       35         0      0     0      0      0      0       0       367      157        5       782         0        21      6206         0        69      3779         0        60        39         0         1        25         0         0      bh  Minority

In [15]:
nyc_10.columns = [x.upper() for x in nyc_10.columns]

nyc_10.columns.values

array(['TRACTID', 'STATE', 'COUNTY', 'TRACT', 'POP10', 'NHWHT10',
       'NHBLK10', 'NTV10', 'ASIAN10', 'HISP10', 'HAW10', 'INDIA10',
       'CHINA10', 'FILIP10', 'JAPAN10', 'KOREA10', 'VIET10', 'MEX10',
       'PR10', 'CUBAN10', 'FAMILY10', 'FHH10', 'HU10', 'VAC10', 'OHU10',
       'OWN10', 'RENT10', 'A18UND10', 'A60UP10', 'A75UP10', 'AGEWHT10',
       'A15WHT10', 'A60WHT10', 'AGEBLK10', 'A15BLK10', 'A60BLK10',
       'AGEHSP10', 'A15HSP10', 'A60HSP10', 'AGEASN10', 'A15ASN10',
       'A60ASN10', 'AGENTV10', 'A15NTV10', 'A60NTV10', 'GLOBD10',
       'GLOBG10'], dtype=object)

### Make them all match the 2000 columns in terms of formatting

In [ ]:
ppl_cols = list(nyc_10.columns.values[5:22,])
house_cols = list(nyc_10.columns.values[-4:-2])

# Read the 2000 Sample csv, take a look, and isolate NYC

In [ ]:
df_s00 = pd.read_csv('DATA/ltdb_std_all_sample/ltdb_std_2000_sample.csv',sep=',', engine='python')
df_s00.head()

In [ ]:
nyc_s00 = df_s00[ (df_s00['state'].eq('NY'))]
nyc_s00 = nyc_s00[  (nyc_s00['county'].eq('Bronx County')) 
                  | (nyc_s00['county'].eq('Kings County')) 
                  | (nyc_s00['county'].eq('Queens County')) 
                  | (nyc_s00['county'].eq('New York County'))]

In [ ]:
print(nyc_s00.shape)
nyc_s00.head(1)

In [ ]:
nyc_s00.columns.values

In [ ]:
sp_list = list(nyc_s00.columns.values[9:])

In [ ]:
def pipeline(df,ppl_list,house_list):
    for x in df.columns.values:
        if x in ppl_list:
            df[x + '%'] = 100 * df[x] / df['POP00']
        elif x in house_list:
            df[x + '%'] = 100 * df[x] / df['HU00']
    # the percentage of non 
    df['NONWHT00%'] = 100*(df.iloc[:,10:14].sum(1)/df['POP00'])
    df.drop(columns = ['HU00%'], axis = 1, inplace = True)
    df.drop(df.columns[9:51],axis=1,inplace=True)
    df.drop(df.columns[4:8],axis=1,inplace=True)